//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMS_Study_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CEMSStudyWebDbEntities : DbContext
    {
        public CEMSStudyWebDbEntities()
            : base("name=CEMSStudyWebDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Part75EMP> Part75EMP { get; set; }
        public virtual DbSet<Part75EMPTableOfContents> Part75EMPTableOfContents { get; set; }
    }
}
