//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMS_Study_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part75PE
    {
        public int Part75PEId { get; set; }
        public string Regulation { get; set; }
        public string SectionName { get; set; }
        public string SectionNumber { get; set; }
        public string SectionHeading { get; set; }
        public string Content { get; set; }
    }
}
