//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMS_Study_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part75EMPTableOfContents
    {
        public int Part75EMPTableOfContentsId { get; set; }
        public string Object { get; set; }
    
        public virtual Part75EMP Part75EMP { get; set; }
    }
}
